### ISSUE TITLE
install error when ADD_TORCH_PACKAGE and potential fix

### ISSUE THREAD

**Issue by ZENGXH** [viorik/extracunn#1]
when I try to install the extracunn using `luarocks make`, there comes:

```
         cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/project/dygroup2/xiaohui/support/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/project/dygroup2/xiaohui/support/torch/install/lib/luarocks/rocks/extracunn/0.1-0" && make
-- Found Torch7 in /project/dygroup2/xiaohui/support/torch/install
CMake Error at /project/dygroup2/xiaohui/support/torch/install/share/cmake/torch/TorchPackage.cmake:11 (ADD_LIBRARY):
  add_library cannot create target "extracunn" because another target with
  the same name already exists.  The existing target is a module library
  created in source directory
  "/project/dygroup2/xiaohui/support/extracunn_src".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  CMakeLists.txt:23 (ADD_TORCH_PACKAGE)


-- Configuring incomplete, errors occurred!
```

Finally I found that it is because the src file has been added as cuda library in 

```
CUDA_ADD_LIBRARY(extracunn MODULE ${src-cuda})
```

By copying the definition of ADD_TORCH_PACKAGE and commend the ADD_LIBRARY fix it

```
      INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR} ${Torch_SOURCE_INCLUDES})


      ### C/C++ sources
      IF(src)      


##      ADD_LIBRARY(${package} SHARED ${src})

        ### Torch packages supposes libraries prefix is "lib"
        SET_TARGET_PROPERTIES(${package} PROPERTIES
          PREFIX "lib"
          IMPORT_PREFIX "lib"
          INSTALL_NAME_DIR "@executable_path/${Torch_INSTALL_BIN2CPATH}")

        INSTALL(TARGETS ${package} 
          RUNTIME DESTINATION ${Torch_INSTALL_LUA_CPATH_SUBDIR}
          LIBRARY DESTINATION ${Torch_INSTALL_LUA_CPATH_SUBDIR})

      ENDIF(src)

      ### lua sources
      IF(luasrc)
        INSTALL(FILES ${luasrc} 
          DESTINATION ${Torch_INSTALL_LUA_PATH_SUBDIR}/${package})
      ENDIF(luasrc)
```

I am wondering that maybe we can make some modification for `torch.cmake` or the cmake file of `extracunn` ?

**Comment by viorik** [comment]
Hi @ZENGXH , 
I never encountered this issue before. Did you maybe have a project already installed called extracunn? I don't know why CUDA_ADD_LIBRARY would be a problem; those are cuda files, hence to me it's normal that they are compiled/built as cuda library. Could you tell me what OS you are running, and what versions of gcc and cmake?

**Comment by ZENGXH** [comment]
Hi viorik,
Thanks for your reply. Here is my configuration:

```
CentOS 6, x86_64 edition
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
cmake version 2.8.12.2
```

I do not have package called extracunn before. Also when I try to install `unsupgpu` I encounter with the same problem and fix in the same way and it works now.

**Comment by viorik** [comment]
The issue reported [here](https://github.com/torch/torch7/issues/270), again on a red hat server, might be similar to what you observe? Good that you got it to work. However, for the moment, I would not make any changes in my cmake, since it works on other distros the way it is now. Thanks for letting me know though.

**Comment by ZENGXH** [comment]
Yeah I think they are quite similar. Thanks a lot for your help!

By the way, I am running the `main-mnist.lua` and encounter with this error:

```
/project/dygroup2/xiaohui/support/torch/install/bin/luajit: ./ConvLSTM.lua:168: attempt to index field 'inputs' (a nil value)
stack traceback:
    ./ConvLSTM.lua:168: in function 'updateOutput'
    ...ui/support/torch/install/share/lua/5.1/rnn/Sequencer.lua:47: in function 'updateOutput'
    ...ui/support/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
    ...i/support/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'updateOutput'
    ...ui/support/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'updateOutput'
    main-mnist.lua:79: in function 'opfunc'
    ...ui/support/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
    main-mnist.lua:107: in function 'main'
    main-mnist.lua:163: in main chunk
    [C]: in function 'dofile'
    ...port/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00405800
```

I have not yet figure out where is the bug and still looking for it. 
I would be really thankful if you have any idea about that.

line 168 of `ConvLSTM.lua` is

```
local input_ = self.inputs[self.step]
```

**Comment by viorik** [comment]
@ZENGXH please reinstall ConvLSTM and rnn package, since there have been recent changes in both. That error makes me think you are running an old version of the code. If you look in the current ConvLSTM.lua, line 168 points to something  completely different.

**Comment by ZENGXH** [comment]
Thanks so much @viorik, You are right. It is because I fork the code long time ago. And it runs well now!
It is really nice of you for pointing that out. I will bear in mind and keep updating.

**Comment by viorik** [comment]
Could you please close this issue, if the problem is solved? 
cheers

**Comment by ZENGXH** [comment]
Sure

**Comment by evgen48** [comment]
Have the same problem with add_library  on following setup: 
3.19.0-58-generic #64~14.04.1-Ubuntu 
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
/home/user/torch/install/bin/luarocks 2.3.0

I had to use @ZENGXH WA with custom ADD_TORCH_PACKAGE

**Comment by byronwwang** [comment]
@ZENGXH Could you tell me where to past the provide codes? Do I needs comments out 'ADD_TORCH_PACKAGE'?

**Comment by ZENGXH** [comment]
@byronwwang it is in the `cMakeList.txt`, you can comments out the line for 'ADD_TORCH_PACKAGE' and then past the codes in the same place.

**Comment by ashwani-pandey** [comment]
@ZENGXH @viorik  Hi, actually I am getting the following error after following the steps that you mentioned : 

> /home/cs15resch11001/extracunn/Huber.cu(22): error: identifier "THCudaTensor_pointwiseApply1" is undefined
> 
> 1 error detected in the compilation of "/tmp/tmpxft_000004ba_00000000-6_Huber.cpp1.ii".
> CMake Error at extracunn_generated_Huber.cu.o.cmake:264 (message):
>   Error generating file
>   /home/cs15resch11001/extracunn/build/CMakeFiles/extracunn.dir//./extracunn_generated_Huber.cu.o
> 
> make[2]: **\* [CMakeFiles/extracunn.dir/./extracunn_generated_Huber.cu.o] Error 1
> make[1]: **\* [CMakeFiles/extracunn.dir/all] Error 2
> make: **\* [all] Error 2

It would be great if you can help me with this!

A very similar issue was described and resolved here : https://github.com/torch/cunn/issues/295#issue-159767279  just 4 days ago, and it happened because of some recent commits to cunn. I guess this error is occurring because of the very same reason.

**Comment by soumith** [comment]
@viorik please patch your repo with similar changes as https://github.com/torch/cunn/pull/296/files

**Comment by viorik** [comment]
@ashwani-pandey I've just patched the repo for compatibility with new cunn. Please let me know if this is fine now.
cheers.
