### ISSUE TITLE
Not able to install extracunn

### ISSUE THREAD

**Issue by mansirankawat** [viorik/extracunn#2]
Hi,

I am not able to install this package.  This error comes when I try to install it. Please help me to identify what is the issue here

Using extracunn-0.1-0.rockspec... switching to 'build' mode
Cloning into 'extracunn'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 0), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (16/16), 9.72 KiB | 0 bytes/s, done.
Checking connectivity... done.
         cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/qk/Apps/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/qk/Apps/torch/install/lib/luarocks/rocks/extracunn/0.1-0" && make  
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found CUDA: /usr/local/cuda-7.5 (found version "7.5") 
-- Found Torch7 in /home/qk/Apps/torch/install
CMake Error at /home/qk/Apps/torch/install/share/cmake/torch/TorchPackage.cmake:11 (ADD_LIBRARY):
  add_library cannot create target "extracunn" because another target with
  the same name already exists.  The existing target is a module library
  created in source directory "/tmp/luarocks_extracunn-0.1-0-6711/extracunn".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  CMakeLists.txt:22 (ADD_TORCH_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_extracunn-0.1-0-6711/extracunn/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

**Comment by viorik** [comment]
Hi @mansirankawat , 
What OS are you using? Is your issue similar to issue #1 ? Maybe the fix suggested there works for you too?

**Comment by mansirankawat** [comment]
Yes that fix seems to work. My OS is Ubuntu 14.0.4 x86_64.
