### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ibrahim5253** [viorik/extracunn#3]
I am having problems installing the package. When I execute `luarocks make` inside the extracunn directory, I get the following errors:
`Missing dependencies for extracunn:
cutorch 

Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 107, done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 107 (delta 8), reused 35 (delta 1), pack-reused 0
Receiving objects: 100% (107/107), 157.05 KiB | 96.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/dungeon_master/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/dungeon_master/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/dungeon_master/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-7601/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.`

**Comment by viorik** [comment]
Hi @ibrahim5253,
It seems the problem comes when installing cutorch. What system configuration do you have (OS, cuda version) ? Does it work to install cutorch separately by running `luarocks install cutorch` ?

**Comment by ibrahim5253** [comment]
@viorik  I don't have Nvidia Graphics card on my system(Ubuntu 14.04, Dell Inspiron 1545, Intel pentium) and hence, cannot install CUDA. Are there any other alternatives?

**Comment by viorik** [comment]
@ibrahim5253 if you plan to run ConvLSTM, you need to implement on CPU or in OpenCL the SpatialConvolutionNoBias layer from this package. The CPU version should be straightforward from what I know, but didn't have time/interest to do it myself.

**Comment by viorik** [comment]
@ibrahim5253 I've just realised that the convolution with no bias is available in nn, so to run ConvLSTM, you can use instead of my SpatialConvolutionNoBias, a normal SpatialConvolution layer and call the function nobias to cancel the bias of that layer.
