### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by cseeker** [viorik/extracunn#4]
Hi, I tried to install 'extracunn'  as explained in readme.
Unzip extracunn-master.zip and go to unzipped directory and then type.
`luarocks make`

However, I got below error message.
` 
                 cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/cseeker/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/cseeker/torch/install/lib/luarocks/rocks/extracunn/0.1-0" && make
-- Found Torch7 in /home/cseeker/torch/install
CMake Error at CMakeLists.txt:24 (TARGET_LINK_LIBRARIES):
  Cannot specify link libraries for target "extracunn" which is not built by
  this project.

-- Configuring incomplete, errors occurred!
See also "/home/cseeker/extracunn-master/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.`

Could you tell me how can I solve this error?

**Comment by viorik** [comment]
Hi @cseeker 
Not sure where the error comes from. Could you try to update your torch/cutorch/nn and then try again compiling?
Check also the file indicated in the error "/home/cseeker/extracunn-master/build/CMakeFiles/CMakeOutput.log", maybe there is some hint there?

**Comment by viorik** [comment]
Also, what is your configuration (OS, GPU)?

**Comment by cseeker** [comment]
I'm sorry. I forgot to write my OS info.
I'm using Ubuntu 14.04 and using Nvidia Geforce GTX Titan Black.
Version of torch is 7.0.
And, re-installed nn and cutorch.
But, problem was not solved.
In CMakeOutput.log, there is nothing about torch or lua.

**Comment by viorik** [comment]
Can you try to replace the code in CMakeLists.txt with the code below? (this is an older version of the file that used to work for me before, but stopped working after I made some updates, but I don't know which updates exactly caused this):

```
CMAKE_MINIMUM_REQUIRED(VERSION 2.8 FATAL_ERROR)
CMAKE_POLICY(VERSION 2.8)

IF(LUAROCKS_PREFIX)
  MESSAGE(STATUS "Installing extracunn through Luarocks")
  STRING(REGEX REPLACE "(.*)lib/luarocks/rocks.*" "\\1" CMAKE_INSTALL_PREFIX  "${LUAROCKS_PREFIX}")
  MESSAGE(STATUS "Prefix inferred from Luarocks: ${CMAKE_INSTALL_PREFIX}")
ENDIF()

FIND_PACKAGE(CUDA REQUIRED)
LIST(APPEND CUDA_NVCC_FLAGS "-arch=sm_30")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,-export-dynamic")

FIND_PACKAGE(Torch REQUIRED)
INCLUDE_DIRECTORIES("${Torch_INSTALL_INCLUDE}/THC")
LINK_DIRECTORIES("${Torch_INSTALL_LIB}")

FILE(GLOB luasrc *.lua)
FILE(GLOB src-cuda *.cu)
CUDA_ADD_LIBRARY(extracunn MODULE ${src-cuda})
ADD_TORCH_PACKAGE(extracunn "${src-cuda}" "${luasrc}" "extra layers in cunn")
TARGET_LINK_LIBRARIES(extracunn luaT THC TH)

IF(LUALIB)
  TARGET_LINK_LIBRARIES(extracunn ${LUALIB})
ENDIF()

 ### Torch packages supposes libraries prefix is "lib"
SET_TARGET_PROPERTIES(extracunn PROPERTIES
  PREFIX "lib"
  IMPORT_PREFIX "lib")

INSTALL(TARGETS extracunn
  RUNTIME DESTINATION "${Torch_INSTALL_LUA_CPATH_SUBDIR}"
  LIBRARY DESTINATION "${Torch_INSTALL_LUA_CPATH_SUBDIR}")

INSTALL(
  FILES
  ${luasrc}
  DESTINATION "${Torch_INSTALL_LUA_PATH_SUBDIR}/extracunn")
```

**Comment by cseeker** [comment]
Thank you very much.
Above code solved the problem.
Installation was done.
