### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yunhunJang** [viorik/extracunn#5]
Hi,

I'm getting trouble with installing extracunn (to use your ConvLSTM package).
The error message I got is

```
 .../extracunn/SpatialCOnvolutionMMNoBias.cu(204): error: identifier "THCudaBlas_gemm" is undiefined
```

I think it is because latest version of cutorch removed THCudaBlas_gemm.

Is it okay to change `THCudaBlas_gemm` to `THCudaBlas_Sgemm`?

**Comment by viorik** [comment]
Hi @yunhunJang 
Thank you for bringing this up. I changed to Sgemm now. Please re-clone and let me know if it works now.  cheers.
