### ISSUE TITLE
spatial conv in torch already as noBias() option

### ISSUE THREAD

**Issue by culurciello** [viorik/extracunn#8]
https://github.com/torch/nn/blob/master/SpatialConvolution.lua#L28

**Comment by viorik** [comment]
Thanks, Eugenio, for the note. I knew about this. But I implemented ConvNoBias for my [ConvLSTM](https://github.com/viorik/ConvLSTM) layer about 10 months ago, and if I am not mistaken, the noBias option didn't exist back then. I am currently working on adding recurrent batch normalisation to ConvLSTM, and in that version of the code I am using the noBias option. Will update soon my ConvLSTM repository.

**Comment by viorik** [comment]
Added [a note](https://github.com/viorik/extracunn/commit/2aadcf877a9507df0f0feda774dd217ced6e398d) in the README about this. Thank you.

**Comment by culurciello** [comment]
great package by the way! thanks for sharing it!
E
